### ISSUE TITLE
java.lang.NoSuchMethodError: 'int net.minecraft.commands.Commands.m_82117_(net.minecraft.commands.CommandSourceStack, java.lang.String)'

### ISSUE THREAD

**Issue by OctavioCore** [lynnpye/scheduler#3]
Hi (Again) :D

A different pack, this time on 1.19.2, plenty of mods. Still running alive and well on ARM64, openjdk 17.0.6

`> java.lang.NoSuchMethodError: 'int net.minecraft.commands.Commands.m_82117_(net.minecraft.commands.CommandSourceStack, java.lang.String)'
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.Cronmc$2.run(Cronmc.java:126)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.8/net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:123)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.Cronmc.opCommand(Cronmc.java:121)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.task.OpHandler$1.run(OpHandler.java:28)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.schedule.CronTask$2.run(CronTask.java:87)
        at LAYER PLUGIN/fmlcore@1.19.2-43.2.8/net.minecraftforge.fml.DistExecutor.safeRunWhenOn(DistExecutor.java:123)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.schedule.CronTask.executeRunnable(CronTask.java:84)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.mcmod.cronmc.api.schedule.CronTask.execute(CronTask.java:64)
        at TRANSFORMER/cronmc@1.19-1.1/com.pyehouse.cronmc.relocated.cron4j.TaskExecutor$Runner.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:833)`
        
 The schedule works, and the console actually shows that error when the tasks are about to be executed. Although I don't usually dabble in Java, a blind guess - Forge introduced a breaking change in handling commands, perhaps?
 
 Thanks for the mod again, honestly at this point I'm just too used to a civilized, fully featured cron implementation to even image coming back to `/schedule` shenanigans, command blocks, and other types of primitive recurrent task handling/scheduling :P
 
 ~S

**Comment by lynnpye** [comment]
Looks like it's getting a stress test across versions if nothing else. :)

Could you provide the cronmc-server.toml?

And is it crashing or is the exception just popping up in the log but the server keeps running? If it's crashing, would you mind adding the crash log?

**Comment by lynnpye** [comment]
Also, does the command being executed ever actually succeed or does it always fail?

**Comment by OctavioCore** [comment]
Config:
[cronmc-server.txt](https://github.com/lynnpye/cronmc/files/11239652/cronmc-server.txt)

The config in there is pretty much "say things from the console, then a bit later execute native Minecraft commands (kill @e)". 
It doesn't crash the server - the exception is thrown to the console in white text, and that's just it. The commands doesn't appear to be ran - they are triggered, fail, then the server just skips the error and moves on.

**Comment by lynnpye** [comment]
It just occurred to me... you're running 1.19.2. I never updated cronmc for anything later than 1.19.1, so I suspect that is the problem.

I'll look into doing a rebuild and posting.

**Comment by OctavioCore** [comment]
Yep, that might be true - I didn't expect patch versions to be as heavily incompatible as they are, however I've run into numerous issues with mods for 1.19.1 absolutely unusable on 1.19.2. Welp, Mojang is now owned by Microsoft, so things not working as they should is now the new bread & butter ;D

Good luck, and let me know if I can provide anything else to help.
